display_errors=Off
log_errors=On
memory_limit=256M
upload_max_filesize=512M
post_max_size=512M
max_execution_time=300
max_input_time=300
date.timezone=America/Sao_Paulo


; OPcache: acelera o PHP mantendo o bytecode compilado em memoria
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=10000
opcache.validate_timestamps=1
opcache.revalidate_freq=60
